add notString
Tatenda-D-Mawoneke/coding-bat pull request #11
Opened 2023-07-08 01:59 UTC by Tatenda-D-Mawoneke

2023-07-10 09:53 UTC, JustinGuedes requested changes

2023-07-10 09:53 UTC, JustinGuedes commented on Warmup-1/notString/test/index.test.ts
> +  it("should return 'not candy' when the parameter value is 'not bad'", () => {
Hmmm strange test description here 🤔

2023-07-10 17:20 UTC, Tatenda-D-Mawoneke commented on Warmup-1/notString/test/index.test.ts
> +  it("should return 'not candy' when the parameter value is 'not bad'", () => {
hmm..hmmmm

2023-07-26 16:13 UTC, JustinGuedes requested changes

2023-07-26 16:13 UTC, JustinGuedes commented on Warmup-1/notString/test/index.test.ts
> +  it("should return 'not candy' when the parameter value is 'not candy'", () => {
Update the test description please

2023-07-26 21:40 UTC, merged